# Generated by Django 3.2.3 on 2021-06-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_profile_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isAdmin',
        ),
    ]
